import { motion } from "framer-motion";
import PageTransition from "../components/PageTransition";
import GlowCard from "../components/GlowCard";

const jobs = [
  {
    title: "Staff Software Engineer",
    company: "Ion Solar",
    period: "July 2024 – Present",
    location: "Remote / Salt Lake City, UT",
    highlights: [
      "Reduced overall development cost from $1.06M/year to $584K/year — a 45% cost reduction.",
      "Reduced a single app's development costs from $840K/year to $50K — a 94% cost reduction.",
      "Accelerated from Engineer to Staff Software Engineer in 1.5 years, eventually assuming technical oversight for the entire company's engineering strategy for a 1,000+ person organization.",
      "Launched 3 new enterprise applications from scratch, defining technical strategy, system design, user experience, and implementation standards in React, React Native, Angular, PHP, and Ruby on Rails.",
      "Led cross-functional engineering teams to develop and scale mission-critical applications, design real-time analytics and BI dashboards, and drive technical excellence through mentorship, code reviews, and scalable architecture.",
    ],
  },
  {
    title: "Backend Software / Data Engineer",
    company: "Pattern",
    period: "November 2021 – July 2024",
    location: "Lehi, UT",
    highlights: [
      "$34M in additional annual revenue generated by personally identifying a key data trend and driving implementation of a data-driven feature through large-scale data analysis and engineering execution.",
      "Built large-scale advertising tech for the largest seller and advertiser on Amazon.com.",
      "Scaled ad tech in a hyper-growth startup, culminating in a successful IPO.",
      "Created machine learning data pipelines, analyzed model outputs, and suggested improvements.",
      "Built backend services and APIs in Ruby on Rails, integrating PostgreSQL and Snowflake to support scalable analytics and advertising and e-commerce operations.",
      "Collaborated cross-functionally with product, data science, and engineering teams to translate insights into production systems aligned with growth objectives.",
      "Enhanced data infrastructure and pipeline performance with Apache Airflow, enabling real-time insights and operational efficiency improvements across business units.",
    ],
  },
  {
    title: "Machine Learning Researcher",
    company: "Brigham Young University",
    period: "Apr 2020 – Aug 2020, Apr 2021 – Aug 2021",
    location: "Provo, UT",
    highlights: [
      "Co-authored a research paper on advancements in Natural Language Processing (NLP).",
      "Developed machine learning models for computer vision and NLP using Python, NumPy, Pandas, and PyTorch, improving model accuracy and efficiency.",
    ],
  },
  {
    title: "Full-Stack Software Engineer",
    company: "BYU Life Sciences IT Services",
    period: "Sep 2019 – July 2020",
    location: "Provo, UT",
    highlights: [
      "Designed and implemented RESTful APIs using C# and .NET Core with a Vue.js frontend.",
      "Modeled and optimized a MySQL database with Entity Framework Core, writing SQL queries and implementing performance improvements that enhanced data access speed and reliability.",
    ],
  },
  {
    title: "Full-Stack Software Engineer Intern",
    company: "Dignity Health Initiatives",
    period: "May 2018 – Aug 2018",
    location: "Phoenix, AZ",
    highlights: [
      "Consolidated error logs from 15 applications into a unified dashboard, reducing troubleshooting time for developers by 40% and cutting costs from disjointed logging services.",
      "Developed a single-page web application using Angular, JavaScript, HTML, and CSS.",
    ],
  },
];

export default function Experience() {
  return (
    <PageTransition>
      <section className="pt-28 pb-20 px-6 sm:px-10 lg:px-20">
        <div className="max-w-4xl mx-auto">
          <div className="animate-slide-up mb-14">
            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-black tracking-tight mb-3">
              <span className="gradient-text">Experience</span>
            </h1>
            <p className="text-neutral-400 text-base sm:text-lg max-w-2xl">
              A track record of shipping impactful products, leading teams, and
              driving measurable business results.
            </p>
          </div>

          <div className="space-y-12">
            {jobs.map((job, i) => (
              <motion.article
                key={job.company + job.title}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.5, delay: i * 0.05 }}
                className="relative pl-6 sm:pl-8 ml-3 border-l-2 border-white/10"
              >
                <div className="absolute left-[-7px] top-1 w-3 h-3 rounded-full bg-accent ring-4 ring-black" />

                <div className="flex flex-col sm:flex-row sm:items-baseline sm:justify-between gap-1 mb-2">
                  <div>
                    <h2 className="text-lg sm:text-xl font-bold text-white">
                      {job.title}
                    </h2>
                    <p className="text-accent-light text-sm font-medium">
                      {job.company}
                    </p>
                  </div>
                  <div className="text-xs sm:text-sm text-neutral-500 sm:text-right whitespace-nowrap mt-1 sm:mt-0">
                    <p>{job.period}</p>
                    <p>{job.location}</p>
                  </div>
                </div>

                <ul className="mt-4 space-y-2.5">
                  {job.highlights.map((h, j) => (
                    <li key={j} className="flex gap-3 text-neutral-300 text-sm leading-relaxed">
                      <span className="mt-2 shrink-0 w-1.5 h-1.5 rounded-full bg-neutral-600" />
                      <span>{h}</span>
                    </li>
                  ))}
                </ul>
              </motion.article>
            ))}
          </div>
        </div>
      </section>

      <section className="pb-20 px-6 sm:px-10 lg:px-20">
        <div className="max-w-4xl mx-auto">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-xl sm:text-2xl font-bold mb-6"
          >
            Other Experience
          </motion.h2>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5"
          >
            {[
              {
                icon: "🏆",
                title: "Head Director, BYU Innovation Competition",
                desc: "Led BYU's largest innovation competition, coordinating teams, sponsors, and participants.",
              },
              {
                icon: "🌍",
                title: "Humanitarian Service",
                desc: "Completed two years of humanitarian service in a developing country. Became fluent in Tagalog.",
              },
              {
                icon: "💰",
                title: "Door-to-Door Sales",
                desc: "Generated over $250,000 in revenue in just four months through direct sales.",
              },
              {
                icon: "📦",
                title: "Open Source",
                desc: "Open source contributor to the MuffinMan Gem.",
              },
            ].map((item) => (
              <GlowCard key={item.title} className="p-5">
                <span className="text-xl mb-2 block">{item.icon}</span>
                <h3 className="font-semibold text-white text-sm mb-2">{item.title}</h3>
                <p className="text-xs text-neutral-400 leading-relaxed">
                  {item.desc}
                </p>
              </GlowCard>
            ))}
          </motion.div>
        </div>
      </section>
    </PageTransition>
  );
}
